### ISSUE TITLE
Unable to login to R studio

### ISSUE THREAD

**Issue by benscott2** [ministryofjustice/data-platform-support#166] opened 2023-07-18 11:37 UTC
### What happened?

Hi,
I am trying to log into R studio but I can't get through the loading screen. I have the same issue twice in the last couple of days so is there anything you could also do to prevent this happening again please?
Thanks!

**Comment by jhackett-ap** [comment] 2023-07-18 14:28
Hi Ben,

I think the problem is your MFA - you should have an email to reset it now. Give that a go and let me know if you're still having trouble.

Cheers
John

**Comment by Gary-H9** [comment] 2023-10-13 14:14
Closing as I believe this is out of date. Please re-open if incorrect.

**Closed by Gary-H9** 2023-10-13 14:14 UTC
Labels: ap-support, control-panel, awaiting-response, auth0
